services:
  - type: web
    name: user-service
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: user-service
    dockerfilePath: user-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

  - type: web
    name: event-catalog-service
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: event-catalog-service
    dockerfilePath: event-catalog-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

  - type: web
    name: booking-service
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: booking-service
    dockerfilePath: booking-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

  - type: web
    name: payment-service
    runtime: docker
    plan: free
    region: frankfurt
    dockerContext: payment-service
    dockerfilePath: payment-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
